batchconvert:
  sets:
  - name: name1
    inputdir: /my/path11
    outputdir: /my/path12
    fileglobpattern: "*.csv"
    filemaxagedays: 5
    format: Barclaycard
  - name: name2
    inputdir: /my/path21
    outputdir: /my/path22
